name: Integration Tests
on: [push, pull request]
jobs:
integration-test:
runs-on: ubuntu-latest
services:
db:
image: postgres:13
ports:
- 5432:5432
env:
POSTGRES_USER: testuser
POSTGRES_PASSWORD: testpassword
POSTGRES_DB: testdb
options: >-
 --health-cmd="pgisready -U testuser"
 --health-interval=10
 --health-timeout=5s
 --health-retries=3
steps:
- name: Checkout code
uses: actions/checkout@v3
-- name: Set up Node.js (example)
uses: actions/setup-node@v3
with:
node-version: '16'
-- name: Install dependencies
run: npm install
- name: Run integration tests
 env:
 DATABASE URL: postgres://test_user:testpassword@localhost:5432/testdb
 run: npm run test:integration

